apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: lumen-slate-ai-microservice
  namespace: PROJECT_ID
spec:
  template:
    spec:
      containers:
        - image: IMAGE_URL
          ports:
            - containerPort: 8080
          env:
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: GOOGLE_API_KEY
                  key: latest
