# deployment-prod.yaml
# Deployment and Service for production
# Uses production Docker image, references prod ConfigMap and Secret
# Includes resource requests/limits and health probes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lumenslate-backend-prod
  labels:
    app: lumenslate-backend
    environment: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lumenslate-backend
      environment: prod
  template:
    metadata:
      labels:
        app: lumenslate-backend
        environment: prod
    spec:
      containers:
        - name: lumenslate-backend
          image: registry.example.com/lumenslate-backend:latest # Production image
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: lumenslate-config-prod
            - secretRef:
                name: lumenslate-secret-prod
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: lumenslate-backend-prod
  labels:
    app: lumenslate-backend
    environment: prod
spec:
  type: ClusterIP
  selector:
    app: lumenslate-backend
    environment: prod
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
