# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.protos import document_service_pb2 as app_dot_protos_dot_document__service__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in app/protos/document_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DocumentServiceStub(object):
    """Document Service for user document storage and management
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadDocument = channel.stream_unary(
                '/document.DocumentService/UploadDocument',
                request_serializer=app_dot_protos_dot_document__service__pb2.UploadDocumentRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_document__service__pb2.UploadDocumentResponse.FromString,
                _registered_method=True)
        self.DownloadDocument = channel.unary_stream(
                '/document.DocumentService/DownloadDocument',
                request_serializer=app_dot_protos_dot_document__service__pb2.DownloadDocumentRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_document__service__pb2.DownloadDocumentResponse.FromString,
                _registered_method=True)
        self.DeleteDocument = channel.unary_unary(
                '/document.DocumentService/DeleteDocument',
                request_serializer=app_dot_protos_dot_document__service__pb2.DeleteDocumentRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_document__service__pb2.DeleteDocumentResponse.FromString,
                _registered_method=True)
        self.ListDocuments = channel.unary_unary(
                '/document.DocumentService/ListDocuments',
                request_serializer=app_dot_protos_dot_document__service__pb2.ListDocumentsRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_document__service__pb2.ListDocumentsResponse.FromString,
                _registered_method=True)
        self.GetDocumentUrl = channel.unary_unary(
                '/document.DocumentService/GetDocumentUrl',
                request_serializer=app_dot_protos_dot_document__service__pb2.GetDocumentUrlRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_document__service__pb2.GetDocumentUrlResponse.FromString,
                _registered_method=True)
        self.GetUsageStats = channel.unary_unary(
                '/document.DocumentService/GetUsageStats',
                request_serializer=app_dot_protos_dot_document__service__pb2.GetUsageStatsRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_document__service__pb2.GetUsageStatsResponse.FromString,
                _registered_method=True)


class DocumentServiceServicer(object):
    """Document Service for user document storage and management
    """

    def UploadDocument(self, request_iterator, context):
        """Upload a document with streaming support for large files
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadDocument(self, request, context):
        """Download a document with streaming support for large files
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDocument(self, request, context):
        """Delete a document and update usage statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDocuments(self, request, context):
        """List documents with filtering and pagination
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocumentUrl(self, request, context):
        """Generate presigned URL for document access
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsageStats(self, request, context):
        """Get user storage usage statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadDocument': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadDocument,
                    request_deserializer=app_dot_protos_dot_document__service__pb2.UploadDocumentRequest.FromString,
                    response_serializer=app_dot_protos_dot_document__service__pb2.UploadDocumentResponse.SerializeToString,
            ),
            'DownloadDocument': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadDocument,
                    request_deserializer=app_dot_protos_dot_document__service__pb2.DownloadDocumentRequest.FromString,
                    response_serializer=app_dot_protos_dot_document__service__pb2.DownloadDocumentResponse.SerializeToString,
            ),
            'DeleteDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDocument,
                    request_deserializer=app_dot_protos_dot_document__service__pb2.DeleteDocumentRequest.FromString,
                    response_serializer=app_dot_protos_dot_document__service__pb2.DeleteDocumentResponse.SerializeToString,
            ),
            'ListDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDocuments,
                    request_deserializer=app_dot_protos_dot_document__service__pb2.ListDocumentsRequest.FromString,
                    response_serializer=app_dot_protos_dot_document__service__pb2.ListDocumentsResponse.SerializeToString,
            ),
            'GetDocumentUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocumentUrl,
                    request_deserializer=app_dot_protos_dot_document__service__pb2.GetDocumentUrlRequest.FromString,
                    response_serializer=app_dot_protos_dot_document__service__pb2.GetDocumentUrlResponse.SerializeToString,
            ),
            'GetUsageStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsageStats,
                    request_deserializer=app_dot_protos_dot_document__service__pb2.GetUsageStatsRequest.FromString,
                    response_serializer=app_dot_protos_dot_document__service__pb2.GetUsageStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'document.DocumentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('document.DocumentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentService(object):
    """Document Service for user document storage and management
    """

    @staticmethod
    def UploadDocument(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/document.DocumentService/UploadDocument',
            app_dot_protos_dot_document__service__pb2.UploadDocumentRequest.SerializeToString,
            app_dot_protos_dot_document__service__pb2.UploadDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/document.DocumentService/DownloadDocument',
            app_dot_protos_dot_document__service__pb2.DownloadDocumentRequest.SerializeToString,
            app_dot_protos_dot_document__service__pb2.DownloadDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document.DocumentService/DeleteDocument',
            app_dot_protos_dot_document__service__pb2.DeleteDocumentRequest.SerializeToString,
            app_dot_protos_dot_document__service__pb2.DeleteDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document.DocumentService/ListDocuments',
            app_dot_protos_dot_document__service__pb2.ListDocumentsRequest.SerializeToString,
            app_dot_protos_dot_document__service__pb2.ListDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocumentUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document.DocumentService/GetDocumentUrl',
            app_dot_protos_dot_document__service__pb2.GetDocumentUrlRequest.SerializeToString,
            app_dot_protos_dot_document__service__pb2.GetDocumentUrlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsageStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document.DocumentService/GetUsageStats',
            app_dot_protos_dot_document__service__pb2.GetUsageStatsRequest.SerializeToString,
            app_dot_protos_dot_document__service__pb2.GetUsageStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
